name: Unit tests

on:
  push:
    # branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.13.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-store
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache purescript + pnpm store
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .spago
            ${{ env.spago_global_cache }}
            output
            ${{ steps.pnpm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}-spago-${{ hashFiles('spago.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
            ${{ runner.os }}-spago-

      - name: Add esbuild and purs-backend-es as dev deps (CI-only)
        # install them locally instead of globally to avoid global pnpm issues
        run: pnpm add -D esbuild@latest purs-backend-es@latest

      - name: Install
        run: pnpm i

      - name: Check formatting
        run: pnpm run check

      - name: Build source
        run: pnpm spago build --pedantic-packages

      - name: Run tests (non-bundled with default esbuild)
        run: pnpm run test

      - name: Run tests (bundled with default esbuild)
        run: pnpm run test:esbuild

      - name: Run tests (bundled with purs-backend-es)
        run: pnpm run test:purs-backend-es
